k9s:
  cluster: arn:aws:eks:us-west-2:473301030746:cluster/boris-cluster-1
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: po
  featureGates:
    nodeShell: false
  proxy: null
