k9s:
  cluster: arn:aws:eks:eu-west-1:335257739080:cluster/onboarding-test-20-3
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: po
  featureGates:
    nodeShell: false
  proxy: null
