k9s:
  cluster: arn:aws:eks:us-west-2:473301030746:cluster/karpenter-with-autoscaler
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
