#!/bin/bash

if [[ -z "$CONFIG_DIR" ]]; then
  CONFIG_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

FONT="CaskaydiaMono Nerd Font"

sketchybar --bar position=top height=36 margin=0 color=$BG_PRIMARY padding_left=10 padding_right=10 topmost=window y_offset=0

default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:SemiBold:17.0"
  label.font="$FONT:SemiBold:14.0"
  icon.color=$FG
  label.color=$FG_DARK
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

source $ITEMS_DIR/apple.sh
source $ITEMS_DIR/aerospace.sh
source $ITEMS_DIR/clock.sh
source $ITEMS_DIR/volume.sh
source $ITEMS_DIR/battery.sh
source $ITEMS_DIR/wifi.sh
source $ITEMS_DIR/input.sh

sketchybar --hotload on

sketchybar --update
