k9s:
  cluster: arn:aws:eks:us-west-2:473301030746:cluster/green-light-test-v2
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: secret
  featureGates:
    nodeShell: false
  proxy: null
