k9s:
  cluster: arn:aws:eks:us-west-2:473301030746:cluster/staging
  namespace:
    active: integration
    lockFavorites: false
    favorites:
      - all
      - argocd
      - zesty-kompass-compute
      - integration
      - zesty-system
      - azure
      - default
      - zesty-k8s
      - karpenter
  view:
    active: context
  featureGates:
    nodeShell: false
  proxy: null
