k9s:
  cluster: arn:aws:eks:eu-west-1:220467647388:cluster/cluster-18-3
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: po
  featureGates:
    nodeShell: false
  proxy: null
