k9s:
  cluster: arn:aws:eks:eu-west-1:672188301118:cluster/production
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - default
  view:
    active: pod
  featureGates:
    nodeShell: false
  proxy: null
