k9s:
  cluster: arn:aws:eks:us-west-2:577926974532:cluster/eks-creator-cluster-test
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - zesty-system
    - all
    - karpenter
    - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
